### ISSUE TITLE
Landing page en version

### ISSUE THREAD

**Issue by lroffia** [vaimee/my2sec#24]
@AlesMarconi @GregorioMonari can you do that asap?

**Comment by lroffia** [comment]
Do it again. Starting from project

**Comment by lroffia** [comment]
Closed

**Comment by lroffia** [comment]
Please translate the following page in EN: https://my2sec.it

**Comment by AlesMarconi** [comment]
https://docs.google.com/document/d/1S40tsvl-DYJG2QdC5n7nZM6oXOyho4Zy/edit#

@GregorioMonari @lroffia ho fatto la traduzione al doc del link. Se avete problemi fatemi sapere; grazie mille

**Comment by lroffia** [comment]
@AlesMarconi get notified?

**Comment by AlesMarconi** [comment]
Ricevuto!

 

Da: Luca Roffia ***@***.***> 
Inviato: martedì 15 novembre 2022 21:52
A: vaimee/my2sec ***@***.***>
Cc: AlessandraM ***@***.***>; Mention ***@***.***>
Oggetto: Re: [vaimee/my2sec] Landing page en version (Issue #24)

 

@AlesMarconi <https://github.com/AlesMarconi>  get notified?
