### ISSUE TITLE
Unable to install. Mac Os 12.4 Apple M1

### ISSUE THREAD

**Issue by lroffia** [vaimee/my2sec#6]
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.22.4)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.4.2)
Collecting nltk
  Using cached nltk-3.7-py3-none-any.whl (1.5 MB)
Collecting scikit-learn
  Using cached scikit_learn-1.1.1-cp310-cp310-macosx_12_0_arm64.whl (7.7 MB)
Requirement already satisfied: tk in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (0.1.0)
Requirement already satisfied: python-dateutil in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.8.2)
Collecting psutil
  Using cached psutil-5.9.1.tar.gz (479 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting deprecation
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting tomlkit
  Using cached tomlkit-0.11.1-py3-none-any.whl (34 kB)
Collecting iso8601
  Using cached iso8601-1.0.2-py3-none-any.whl (9.7 kB)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting persistqueue
  Using cached persistQueue-0.1.6.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... done
**ERROR: Could not find a version that satisfies the requirement webbrowser (from versions: none)
ERROR: No matching distribution found for webbrowser**

**Comment by DitucSpa** [comment]
Removed "webbrowser" from the requirements file (the package is installed by default)
