### ISSUE TITLE
Fixing GUI to select ActivityType

### ISSUE THREAD

**Issue by lroffia** [vaimee/my2sec#9]
<img width="1213" alt="Schermata 2022-08-04 alle 10 59 59" src="https://user-images.githubusercontent.com/15211889/182784074-6bfc6e93-54e7-4100-bca6-e4198db1b2d3.png">

1. Adjust the column size so that the "working" "not working" is close to the event description
2. Allow full screen

This would make filling the form easier. Thank you!

**Comment by DitucSpa** [comment]
Limited the label width (some URLs are too long for the pages);
Reduced the Combo Boxes Length;
Anchored the text of Label to LEFT;
With canvas and scrollbar it is impossible to enable the full screen mode, due to some GUI problems with Vertical Scrollbar.
